name: Create Jira issue
on:
  issues:
    types: [opened]

jobs:
  create-issue-team-member-1:
    name: Create Jira issue for Team Member 1
    runs-on: ubuntu-latest
    if: github.actor == 'team_member_1_username' # 특정 팀원만 실행
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_TEAMMEMBER1 }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL_TEAMMEMBER1 }}

      - name: Create Issue
        uses: atlassian/gajira-create@v3
        with:
          project: KAN
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: "${{ github.event.issue.html_url }}"

  create-issue-team-member-3:
    name: Create Jira issue for Team Member 3
    runs-on: ubuntu-latest
    if: github.actor == 'team_member_3_username' # 다른 팀원만 실행
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN_TEAMMEMBER3 }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL_TEAMMEMBER3 }}

      - name: Create Issue
        uses: atlassian/gajira-create@v3
        with:
          project: KAN
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: "${{ github.event.issue.html_url }}"
